Merging `main` onto `stable` to create a stable release package and to secure the code base
wisdom-oss/golang-kong-access pull request #1
Opened 2022-10-18 09:11 UTC by dr4hcu5-jan

This PR is used to merge the main brach to a stable base

2022-10-18 13:28 UTC, cptpiepmatz requested changes

2022-10-18 13:28 UTC, cptpiepmatz commented on boolFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(upstreamName) == "" {
		return false, errors.New("empty upstreamName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on boolFunctions.go
> +func IsAddressInUpstreamTargetList(targetAddress string, upstreamName string) (bool, error) {
comment here

2022-10-18 13:28 UTC, cptpiepmatz commented on boolFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(targetAddress) == "" {
		return false, errors.New("empty target address")
	}
	if strings.TrimSpace(upstreamName) == "" {
		return false, errors.New("empty upstreamName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on boolFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return false, errors.New("empty service name supplied")
	}
	if strings.TrimSpace(upstreamName) == "" {
		return false, errors.New("empty upstream name supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on boolFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return false, errors.New("empty service name supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on boolFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return false, errors.New("empty service name supplied")
	}
	if strings.TrimSpace(path) == "" {
		return false, errors.New("empty path supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on boolFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return false, errors.New("empty service name supplied")
	}
	if strings.TrimSpace(pluginName) == "" {
		return false, errors.New("empty plugin name supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(upstreamName) == "" {
		return false, errors.New("empty upstream upstreamName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	response, err := http.PostForm(gatewayAPIURL+"/upstreams", requestBody)
```suggestion
	response, err := http.PostForm(gatewayAPIURL + "/upstreams", requestBody)
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(targetAddress) == "" {
		return false, errors.New("empty targetAddress supplied")
	}
	if strings.TrimSpace(upstreamName) == "" {
		return false, errors.New("empty upstreamName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	response, err := http.PostForm(gatewayAPIURL+"/upstreams/"+upstreamName+"/targets", requestBody)
```suggestion
	response, err := http.PostForm(gatewayAPIURL + "/upstreams/" + upstreamName + "/targets", requestBody)
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return false, errors.New("empty serviceName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	response, err := http.PostForm(gatewayAPIURL+"/services", requestBody)
```suggestion
	response, err := http.PostForm(gatewayAPIURL + "/services", requestBody)
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +			"httpStatus": response.Status}).Error("An unexpected response code was received from the api gateway")
```suggestion
		logger.WithFields(log.Fields{
		  "httpCode": response.StatusCode,
			"httpStatus": response.Status
	  }).Error("An unexpected response code was received from the api gateway")
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return false, errors.New("empty serviceName supplied")
	}
	if strings.TrimSpace(path) == "" {
		return false, errors.New("empty path supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	response, err := http.PostForm(gatewayAPIURL+"/services/"+serviceName+"/routes", requestBody)
```suggestion
	response, err := http.PostForm(gatewayAPIURL + "/services/" + serviceName + "/routes", requestBody)
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return false, errors.New("empty service name supplied")
	}
	if strings.TrimSpace(pluginName) == "" {
		return false, errors.New("empty plugin name supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +			requestBody.Add("config."+configurationKey, configurationValue)
```suggestion
			requestBody.Add("config." + configurationKey, configurationValue)
```

2022-10-18 13:28 UTC, cptpiepmatz commented on createFunctions.go
> +	response, err := http.PostForm(gatewayAPIURL+"/services/"+serviceName+"/plugins", requestBody)
```suggestion
	response, err := http.PostForm(gatewayAPIURL + "/services/" + serviceName + "/plugins", requestBody)
```

2022-10-18 13:28 UTC, cptpiepmatz commented on enums.go
> +package golang_kong_access
Erkläre wofür das hier ist

2022-10-18 13:28 UTC, cptpiepmatz commented on functions.go
> +	useSSL = false
Immer hier `false`

2022-10-18 13:28 UTC, cptpiepmatz commented on helpers.go
> +func stringArrayContains(a []string, s string) bool {
comment here

2022-10-18 13:28 UTC, cptpiepmatz commented on readFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return nil, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(upstreamName) == "" {
		return nil, errors.New("empty upstream upstreamName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on readFunctions.go
> +func ReadServiceConfiguration(serviceName string) (*ServiceConfiguration, error) {
comment here

2022-10-18 13:28 UTC, cptpiepmatz commented on readFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return nil, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return nil, errors.New("empty serviceName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on readFunctions.go
> +func ReadRouteConfigurationList(serviceName string) (*RouteConfigurationList, error) {
comment here

2022-10-18 13:28 UTC, cptpiepmatz commented on readFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return nil, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return nil, errors.New("empty serviceName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on readFunctions.go
> +			"httpStatus": response.Status}).Error("An unexpected response code was received from the api gateway")
```suggestion
		logger.WithFields(log.Fields{
			"httpCode": response.StatusCode,
			"httpStatus": response.Status
	  }).Error("An unexpected response code was received from the api gateway")
```

2022-10-18 13:28 UTC, cptpiepmatz commented on readFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return nil, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return nil, errors.New("empty serviceName supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on responses.go
> +package golang_kong_access
erklär wofür die Dinger hier sind

2022-10-18 13:28 UTC, cptpiepmatz commented on structs.go
> +package golang_kong_access
Hier auch Datentypen erklären

2022-10-18 13:28 UTC, cptpiepmatz commented on updateFunctions.go
> +func UpdateServiceHost(serviceName string, newHost string) (bool, error) {
comment here

2022-10-18 13:28 UTC, cptpiepmatz commented on updateFunctions.go
> +	}
```suggestion
	if strings.TrimSpace(gatewayAPIURL) == "" {
		return false, errors.New("the connection to the api gateway was not set up")
	}
	if strings.TrimSpace(serviceName) == "" {
		return false, errors.New("empty service name supplied")
	}
	if strings.TrimSpace(newHost) == "" {
		return false, errors.New("empty new host supplied")
	}
```

2022-10-18 13:28 UTC, cptpiepmatz commented on updateFunctions.go
> +	request, err := http.NewRequest("PATCH", gatewayAPIURL+"/services/"+serviceName,
```suggestion
	request, err := http.NewRequest("PATCH", gatewayAPIURL + "/services/" + serviceName,
```

2022-10-18 13:28 UTC, cptpiepmatz commented on updateFunctions.go
> +			"httpStatus": response.Status}).Error("An unexpected response code was received from the api gateway")
```suggestion
		logger.WithFields(log.Fields{
		  "httpCode": response.StatusCode,
			"httpStatus": response.Status
		}).Error("An unexpected response code was received from the api gateway")
```

2022-11-01 13:58 UTC, captainsuchard commented
@cptpiepmatz Please re-review this code for any outstanding issues

2022-11-21 14:27 UTC, cptpiepmatz requested changes
not all threads are actually resolved

2024-01-25 17:37 UTC, closed without merging